require_relative './services/base'
require_relative './services/bulk'
require_relative './services/campaign_management'
require_relative './services/customer_management'
require_relative './services/reporting'
